### ISSUE TITLE
Request to add check for CSCvw33061

### ISSUE THREAD

**Issue by monrog2** [datacenter/ACI-Pre-Upgrade-Validation-Script#10]
CSCvw33061 - Prevent "internal" Encap Blocks (AVE) from leaf programming to avoid overlapping VLAN VNID behavior

https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061

**Comment by monrog2** [comment]
Pulled from #39

Validation Type
[ ] - Fault

[X] - Config

[ ] - Bug

[ ] - Other

What needs to be validated
for fvnsEncapBlk.role=internal, since ACI 4.2(6m) or 5.2(1g) , the corresponding stpAllocEncapBlkDef is deleted post upgrade, as a result, those vlans are deleted from the related switch. If they were used for any user tenant before, outage can be expected.

Why it needs to be validated
Outage can be triggered post upgrade if customer is not aware of this behavior change, introduced by [CSCvw33061]

Additional context
This behavior change is publicly release noted, documented however we see customer's still facing this trouble.

**Comment by wilsonbc2** [comment]
`______________________________________________________________________________________________________________________________________________________________ test_pos_internal_vlanpool_check _______________________________________________________________________________________________________________________________________________________________
-------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
              Starting Positive internal_vlanpool_check ... 
[Check  1/6] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  Target Version  VLAN Pool        Warning
  --------------  ---------        -------
  5.2(2a)         jr-dynamic-pool  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

  Recommended Action: Ensure any VLAN Encap blocks explicitly used for leaf front panel VLAN programming are set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061


[Check  2/6] Internal VLAN Pool Check...                                                                                             PASS
[Check  3/6] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  Target Version  VLAN Pool        Warning
  --------------  ---------        -------
  5.2(6a)         jr-dynamic-pool  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

  Recommended Action: Ensure any VLAN Encap blocks explicitly used for leaf front panel VLAN programming are set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061


[Check  4/6] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  Target Version  VLAN Pool        Warning
  --------------  ---------        -------
  4.2(7d)         jr-dynamic-pool  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

  Recommended Action: Ensure any VLAN Encap blocks explicitly used for leaf front panel VLAN programming are set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061


[Check  5/6] Internal VLAN Pool Check...                                                                                             PASS
______________________________________________________________________________________________________________________________________________________________ test_neg_internal_vlanpool_check _______________________________________________________________________________________________________________________________________________________________
-------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
              Starting Negative internal_vlanpool_check ... 
[Check  1/6] Internal VLAN Pool Check...                                                                                             PASS
[Check  2/6] Internal VLAN Pool Check...                                                                                             PASS
[Check  3/6] Internal VLAN Pool Check...                                                                                             PASS
[Check  4/6] Internal VLAN Pool Check...                                                                                             PASS
[Check  5/6] Internal VLAN Pool Check...                                                                                             PASS
================================================================================================================================================================== 11 passed in 0.09 seconds ==================================================================================================================================================================
`

**Comment by wilsonbc2** [comment]
Check working on live script..Committing changes.

admin@fab3-apic1:techsupport> python aci-preupgrade-validation-script.py
    ==== 2022-11-21T12-52-28-0500 ====

Enter username for APIC login          : admin
Enter password for corresponding User  :

Checking current APIC version (switch nodes are assumed to be on the same version)...5.2(7f)

Gathering APIC Versions from Firmware Repository...

[1]: aci-apic-dk9.5.2.7f.bin
[2]: aci-apic-dk9.6.0.51l.bin

What is the Target Version?     : 1

You have chosen version "aci-apic-dk9.5.2.7f.bin"
...
[Check 40/40] Internal VLAN Pool Check...                                                                          FAIL - OUTAGE WARNING!!
  Target Version           VLAN Pool        Warning
  --------------           ---------        -------
  aci-apic-dk9.5.2.7f.bin  jr-dynamic-pool  VLAN Pool contains an encap block with role "internal" and is associated to a non-AVE domain

  Recommended Action: Ensure any VLAN Encap blocks explicitly used for leaf front panel VLAN programming are set to "external (on the wire)"
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvw33061



=== Summary Result ===

PASS                     : 32
FAIL - OUTAGE WARNING!!  :  3
FAIL - UPGRADE FAILURE!! :  2
MANUAL CHECK REQUIRED    :  1
N/A                      :  2
ERROR !!                 :  0
TOTAL                    : 40



=== Summary Result ===

PASS                     : 32
FAIL - OUTAGE WARNING!!  :  3
FAIL - UPGRADE FAILURE!! :  2
MANUAL CHECK REQUIRED    :  1
N/A                      :  2
ERROR !!                 :  0
TOTAL                    : 40
