### ISSUE TITLE
Request to add check for CSCvv30303

### ISSUE THREAD

**Issue by monrog2** [datacenter/ACI-Pre-Upgrade-Validation-Script#11]
CSCvv30303 - ACI: Same subnet under BD and EPG with different scope is a misconfig

## Conditions:
Having a configuration where a given subnet is defined under both an EPG as well as its corresponding BD, however both subnet definitions have a different combination of "scope" definitions; [private, public, shared]

This config is technically and has always been considered a mis-configuration.

## Workaround:
Ensure that the subnet scope on the bridge domain and EPG are the same.

**Comment by jeestr4d** [comment]
Results from pytest

tests/subnet_scope_check/test_subnet_scope_check.py::test_logic[icurl_outputs0-FAIL - OUTAGE WARNING!!] PASSED                                                     [ 49%]
tests/subnet_scope_check/test_subnet_scope_check.py::test_logic[icurl_outputs1-PASS] PASSED                                                                        [ 49%]
