### ISSUE TITLE
Check `acidiag verifyapic` for cert validity if cver below 3.2.7f

### ISSUE THREAD

**Issue by monrog2** [datacenter/ACI-Pre-Upgrade-Validation-Script#13]
goal would be to catch failures in acidiag verify apic and address them before upgrading to versions 3.2.7f+

In below example, we would flag on `PID:UCSC-C220-M3S`
```
acidiag verifyapic
openssl_check: certificate details
subject= CN=XXXXXXXXXX,serialNumber=PID:UCSC-C220-M3S  SN:XXXXXXXXXX
issuer= CN=Cisco Manufacturing CA,O=Cisco Systems
notBefore=Nov 11 15:32:41 2021 GMT
notAfter=May 14 20:25:41 2029 GMT
openssl_check: passed
openssl_check: certificate details
subject= /serialNumber=PID:UCSC-C220-M3S  SN:XXXXXXXXXX/CN=XXXXXXXXXX
Certificate doesn't match APIC format
apic_cert_format_check: failed

**Comment by welkin0** [comment]
I have the code ready,  can you allow me to push the code.

**Comment by welkin0** [comment]
https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script/blob/welkin-issue-13/aci-preupgrade-validation-script.py

**Comment by takishida** [comment]
Susceptible versions too old. No update in PR for long time. Closing it for now.
