### ISSUE TITLE
APIC 5.2(8h) - SSH login fails because of HostKeyAlgorithms=+ssh-dss"

### ISSUE THREAD

**Issue by x84net** [datacenter/ACI-Pre-Upgrade-Validation-Script#136]
(use upvote :thumbsup: for attentions)
**Describe the bug**
ACI-Pre-Upgrade-Validation-Script fails because SSH login on APICs fails with `HostKeyAlgorithms=+ssh-dss`. 
First sign of this is `ls command via ssh failed due to:failed to login to host`.

An manual SSH attempt using the options listed in line 182 + 183 with an additional `-vvv` ends with `Unable to negotiate with <IP address> port 22: no matching host key type found. Their offer: ssh-rsa`.

After commenting out line 183: `no_verify += " -o HostKeyAlgorithms=+ssh-dss"` ACI-Pre-Upgrade-Validation-Script works as expected.

**To Reproduce**
Manual SSH connect from one APIC to another with ssh-dss options: 
`ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-dss <USERNAME>@<HOSTNAME> -p 22`
=> FAIL

Manual SSH connect from one APIC to another without ssh-dss options: 
`ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null <USERNAME>@<HOSTNAME> -p 22`
=> SUCCESS

**APIC Version**
```
<APIC Host 1># show version
 Role        Pod    Node    Name            Version
 ----------  -----  ------  --------------  ---------
 controller  1      1       <APIC Host 1>   5.2(8h)
 controller  2      2       <APIC Host 2>   5.2(8h)
 controller  2      3       <APIC Host 3>   5.2(8h)
```

**Comment by wilsonbc2** [comment]
Duplicate issue of #133. Closing and will fix under other issue.
