### ISSUE TITLE
NewValidation: ieee-rs-fec support for only certain switches 

### ISSUE THREAD

**Issue by santacruzscott76** [datacenter/ACI-Pre-Upgrade-Validation-Script#137]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[X ] - Config

[ ] - Bug

[ ] - Other

### What needs to be validated

ieee-rs-fec is up to a F5 on a N9K-C93180YC-EX on 14.2.
After upgrade to 5.2 port is down - with F1186 
ieee-rs-fec is only supported certain switches - FX and up - https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Cisco_ACI_and_Forward_Error_Correction.html#Cisco_Reference.dita_5cef69b3-b7fa-4bde-ba60-38129c9e7d82 

### Why it needs to be validated
After upgrade links will be down on those nodes and may need to rollback or change the FEC if possible - some nodes only support ieee-rs-fec like F5 VELOS

### Additional context
N/A

**Comment by wilsonbc2** [comment]
-EX only supports FC-FEC for 25G ports so if the port is still coming up on the older version it is a misconfiguration. 
https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-743149.html#Switchmodels

We can add an additional check for this.

**Comment by santacruzscott76** [comment]
Thans,

I just got another case now with the same issue and a ACI mini but and lost connectivity to the sysnergy…..

: )

Regards,

Scott Sheldon
Technical Consulting Engineer
Global CX Centers - ACI
Working hours: 0800 - 1600 Eastern US Daylight Time (GMT -4)
Email: ***@***.***
Phone: + 1 408-527-5677
-----------------------------------------

Direct Manager: Beatriz Araiza Bermudez
Phone: 9195745390, 5513292749
Email:  ***@***.******@***.***>

Cisco Contact Numbers: 1-800-553-2447 or  Cisco Worldwide Support Contacts
Looking for an instant update on your case?
Connect with me via TAC Connect Bot!
Teams: ***@***.*** or learn more here

***@***.***
