### ISSUE TITLE
Validate target image integrity to avoid corrupted image

### ISSUE THREAD

**Issue by welkin0** [datacenter/ACI-Pre-Upgrade-Validation-Script#14]
The current image validation makes sure all apics has same md5sum for the target image, which assumed that customer has validated the image against CCO release md5 before uploading to APIC. 

It would be great to enhance this script to use CCO release's md5sum as single source of truth for validation, this will be very helpful to capture the corrupted image as well as upgrade failure.

**Comment by welkin0** [comment]
https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script/blob/welkin-issue-14/aci-preupgrade-validation-script.py

**Comment by monrog2** [comment]
Related MR references built in APIC MD5 logic and flags if corrupt image is detected.
