### ISSUE TITLE
APIC CA Cert Validation... openssl cmd issue, send logs to TAC 

### ISSUE THREAD

**Issue by prkrishn** [datacenter/ACI-Pre-Upgrade-Validation-Script#142]
**Describe the bug**
Similar to issue #120 but per Gabe fiing a new issue since #120 was not fully root caused.  When running latest pre upgrade script, test APIC CA Cert Validation fails if there are any temp* or gen.cnf files in directory which would have been created when the script was run by a different user and if a different user runs it next time.

apic1# ls -al
total 292
drwx------  2 admin admin   4096 Jul 26 18:54 .
drwxrwx--- 22 ifc   admin  24576 Jul 11 17:13 ..
-rw-r--r--  1 admin admin 165381 Jul 11 17:13 aci-preupgrade-validation-script.py <<----
-rw-r--r--  1 admin admin    352 Jul 26 18:54 gen.cnf
-rw-------  1 admin admin  46128 Jul 11 17:15 preupgrade_validator_2024-07-11T17-13-55+0000.tgz
-rw-r--r--  1 admin admin  45402 Jul 26 18:54 preupgrade_validator_2024-07-26T18-52-27+0000.tgz
apic1#
**Script output**
[Check 55/65] Internal VLAN Pool...                                                                                                   PASS
[Check 56/65] APIC CA Cert Validation... openssl cmd issue, send logs to TAC                                                      ERROR !! <<---
[Check 57/65] FabricDomain Name...                                                                                                    PASS

Workaround:
Login as the other user which created temp* or gen.cnf and delete them or run the script by logging in as that user.

**Comment by monrog2** [comment]
was able to get access to setup and confirmed this is the same as #120 , will work on the fix and link it to that one.

closing this one as Dup of @120
