### ISSUE TITLE
Spine SUP HW Revision should not fail when destination ACI code is fixed version.

### ISSUE THREAD

**Issue by jcalzad** [datacenter/ACI-Pre-Upgrade-Validation-Script#149]
**Describe the enhancement**
Version handling needs to be adjusted to not trigger failure of SUP HW Revision check when destination code is fixed version.

**Current behavior/output**
```
Gathering APIC Versions from Firmware Repository...

[1]: aci-apic-dk9.5.2.7g.bin
[2]: aci-apic-dk9.5.2.8h.bin

You have chosen version "5.2(8h)" 

...

[Check 49/49] Spine SUP HW Revision...                                                                             FAIL - OUTAGE WARNING!!
  Pod  Node  Sup Slot   Part Number
  ---  ----  --------   -----------
  1    303   supslot-1  73-18570-02
  1    303   supslot-2  73-18570-02
  1    304   supslot-1  73-18570-02
  1    304   supslot-2  73-18570-02

  Recommended Action: Do not upgrade yet. Contact TAC and share these results.
  Reference Document: https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwb86706 
```
**Suggested behavior/output**
Instead of the "FAIL - OUTAGE WARNING" message, something similar to "N/A - Destination code is fixed"

**To Reproduce**
Steps to reproduce the behavior such as:
1. Run pre-upgrade validation script on fabric with modular spine that includes part numbers listed above.
2. Run the script on current version of 5.x with any target version

**Additional context**
Note on currently on line 2883 suggest this as well - "# TODO: Add tversion handling when CSCwb86706 is fixed."

**Comment by monrog2** [comment]
combine with #140
