### ISSUE TITLE
Relax `Features that need to be Disabled prior to Upgrade` check for pre-installed apps

### ISSUE THREAD

**Issue by monrog2** [datacenter/ACI-Pre-Upgrade-Validation-Script#19]
Currently this check will flag on every app that is enabled, which includes the pre-installed apps.

Pre-installed apps typically cannot be disabled, only removed. We have received confirmation that upgrading with pre-installed apps enabled should not pose an issue to the upgrade. 

As such, this check needs to be relaxed for such apps including:

- Cisco_NIBASE (ACI version 4.2+)
- Nexus Insights Cloud Connector (ACI Version 5.2+)
- Cisco_ApicVision
- Base Package apps:
  - Search
  - APIC Postman
  - Contract Viewer
  - VisuDash

**Comment by takishida** [comment]
The default apps ('IntersightDC', 'NIALite', 'NIBASE', 'ApicVision') are already covered.
The Base Package apps are no longer pre-installed, which makes this issue irrelevant for most of the recent versions.
