### ISSUE TITLE
Add check for F606755 as part of CSCwb67893

### ISSUE THREAD

**Issue by ristainoj** [datacenter/ACI-Pre-Upgrade-Validation-Script#24]
fault F606755 should be checked before upgrade to see if there is any l3out configuration which had failed.

POD6-APIC-4# moquery -c faultInst -f 'fault.Inst.code=="F606755"'
Total Objects shown: 1
 
# fault.Inst
code             : F606755
ack              : no
cause            : fsm-failed
changeSet        :
childAction      :
created          : 2022-04-21T13:36:16.485+00:00
delegated        : no
descr            : [FSM:FAILED]: Configure EpP for EPg EXT_NET_NETBACKUP(TASK:ifc:policymgr:FvEPgEpP)
dn               : uni/tn-PRODUCTION/out-NETBACKUP_L3OUT/instP-EXT_NET_NETBACKUP/fault-F606755
domain           : infra
highestSeverity  : major
lastTransition   : 2022-04-21T13:36:16.485+00:00
lc               : raised
modTs            : never
occur            : 1
origSeverity     : major
prevSeverity     : major
rn               : fault-F606755
rule             : fsm-ep-pfsm-fail
severity         : major
status           :
subject          : task-ifc-policymgr-fvepg-epp
type             : config
uid              : 

If this is raised, it could be because there is a duplication of the node profile/logical interface profile with an EIGRP neighborship.  The duplication raises this fault, and after upgrade to a version with PD it can cause PM to crash.  This has a cascading affect and should be added as a check.

**Comment by welkin0** [comment]
thanks Joey, I will be working on this.

**Comment by takishida** [comment]
No one hit this defect since 2022.
