### ISSUE TITLE
Upgrading to 5.2(4) from 4.x can cause /32 static routes to not be installed in FIB 

### ISSUE THREAD

**Issue by scsheldo** [datacenter/ACI-Pre-Upgrade-Validation-Script#25]
This seems to be a intended check that the SW does
If it sees /32 static route that also is overlapping with a BD subnet range on the leaf it will not install it into the FIB
RIB yes
The BL with the static route is not affected but other leaf nodes that receive this update from BGP are.
There is no fault thrown as of now and I opened up the issue with devs already
Seems to be related to this https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/Cisco-ACI-Floating-L3Out.html#Cisco_Concept.dita_2752bf03-c688-42c0-8721-4d463bd2c4e6
CSCwb91766

**Comment by jeestr4d** [comment]
Fix for #25 is https://github.com/jeestr4d/ACI-Pre-Upgrade-Validation-Script/tree/Issue25
local pytest results:

tests/static_route_overlap_check/test_static_route_overlap_check.py::test_logic[icurl_outputs0-4.2(7f)-5.2(8h)-FAIL - OUTAGE WARNING!!] PASSED                     [ 56%]
tests/static_route_overlap_check/test_static_route_overlap_check.py::test_logic[icurl_outputs1-4.2(7f)-5.2(8h)-FAIL - OUTAGE WARNING!!] PASSED                     [ 56%]
tests/static_route_overlap_check/test_static_route_overlap_check.py::test_logic[icurl_outputs2-5.0(1h)-6.2(8h)-PASS] PASSED                                        [ 57%]

**Comment by monrog2** [comment]
merged
