### ISSUE TITLE
NewValidation: APIC must be in Legacy Boot mode. UEFI mode will cause dataconv to fail.

### ISSUE THREAD

**Issue by monrog2** [datacenter/ACI-Pre-Upgrade-Validation-Script#40]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[X] - Config

[ ] - Bug

[ ] - Other

### What needs to be validated
APIC should be set to boot mode Legacy. 

### Why it needs to be validated
UEFI is not supported and can specifically cause dataconv to fail during an APIC upgrade.

### Additional context
[APIC Upgrade: dataconv fails due to unhandled get_apic_model() IndexError
](https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwc58577)

**Comment by monrog2** [comment]
#37

**Comment by takishida** [comment]
Not reproduceable issue, no recent users hitting this.
