### ISSUE TITLE
Route-target Type validation for GOLF 

### ISSUE THREAD

**Issue by welkin-he** [datacenter/ACI-Pre-Upgrade-Validation-Script#42]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[x] - Config

[ ] - Bug

[ ] - Other

### What needs to be validated
for every CTX listed by l3ext.GlobalCtxName,  if bgp.RtTarget.rt of that vrf starts with "extended:", and current version is older than 4.2(1a) and target version is equal or newer than 4.2(1a), we should alert outage for customer before upgrade.

### Why it needs to be validated
we see customer with GOLF deployed hit outage after upgrading from 3.2 to 4.2, caused by export route-target not deployed to BGP.

### Additional context
The enforcement of route target type was set since 4.2(1i).

**Comment by monrog2** [comment]
#43
