### ISSUE TITLE
NewValidation: Compare apicca.crt and apicca.key before upgrade.

### ISSUE THREAD

**Issue by lovsharm** [datacenter/ACI-Pre-Upgrade-Validation-Script#45]
(use upvote :thumbsup: for attentions)
### Validation Type
[ missing Cert can cause spine reload due to nxqmtt crash in 5.2.x] - Fault

[ check apic cert corruption] - Config

[ CSCvy35257] - Bug

[ ] - Other

### What needs to be validated
verify if both CLI return same value, if same, check pass, else recover cert before the upgrade
openssl rsa -modulus -noout -in /securedata/apicca/apicca.key
openssl x509 -modulus -noout -in /securedata/apicca/apicca.crt

### Why it needs to be validated
it can cause Spine crash on 5.2.6e due to CSCwc74242

### Additional context
Add any other context about the feature request here.

**Comment by monrog2** [comment]
Below commands require root access
```
openssl rsa -modulus -noout -in /securedata/apicca/apicca.key
openssl x509 -modulus -noout -in /securedata/apicca/apicca.crt

**Comment by welkin-he** [comment]
https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script/tree/welkin-issue-45
