### ISSUE TITLE
Verify [Check 43/43] APIC CA Cert Validation works in 3.2 release

### ISSUE THREAD

**Issue by lingwa00** [datacenter/ACI-Pre-Upgrade-Validation-Script#47]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[check apic cert corruption] - Config

[CSCvy35257] - Bug

[ ] - Other

### What needs to be validated
verify if both CLI return same value, if same, check pass, else recover cert before the upgrade
openssl rsa -noout -modulus -in /securedata/apicca/apicca.key | openssl md5
openssl x509 -noout -modulus -in /securedata/apicca/apicca.crt | openssl md5

### Why it needs to be validated
F1419 service failed fault raised after apic upgrade.

### Additional context
Checking item 43 failed to identify the issue in 3.2(5e) release. Please help on verification.

**Comment by monrog2** [comment]
above cmds are root only, and the script is currently designed to be run as a non-root user.

@welkin-he was looking at any updates that could be done to the existing to more consistently catch this one.

**Comment by welkin-he** [comment]
The enhancement has been implemented by the introduction of apic_ca_cert_validation
