### ISSUE TITLE
`L3Out Subnets (F0467 prefix-entry-already-in-use)` does not work on older switch versions

### ISSUE THREAD

**Issue by lingwa00** [datacenter/ACI-Pre-Upgrade-Validation-Script#48]
(use upvote :thumbsup: for attentions)
### Validation Type
[F0467(prefix-entry-already-in-use)] - Fault

[Same subnet with import-Security scope configured on different L3outs in same vrf] - Config

[ ] - Bug

[ ] - Other

### What needs to be validated
Same subnet with import-Security scope configured on different L3outs in same vrf

### Why it needs to be validated
After upgrade from 3.2(5e) to 5.2(5c), F0467(prefix-entry-already-in-use) fault raised when same subnet with import-Security scope configured on different L3outs in same vrf. The configuration not supported in 5.2 release. Based on network design/configuration, the configuration issue may have traffic impact. 

### Additional context
[Check 20/43] L3Out Subnets (F0467 prefix-entry-already-in-use) fail to identify the issue in 3.2(5e) release in my case.

**Comment by takishida** [comment]
@lingwa00 

If I'm reading it correctly, you are requesting to fix the existing check "L3Out Subnets (F0467 prefix-entry-already-in-use)" that didn't work on your setup instead of requesting a new validation, correct?

Even in that case, I'm seeing faults "F0467 prefix-entry-already-in-use" getting raised on 3.2(5e) and the script detecting them correctly.
Can you please provide more data (logs, outputs from the script etc.)?

**`moquery`**
```
admin@f1-apic1:techsupport> acidiag version
3.2.5e
admin@f1-apic1:techsupport> moquery -c faultInst -f 'fault.Inst.descr*"prefix-entry-already-in-use"' | egrep '^#|descr|dn'
# fault.Inst
descr            : Configuration failed for uni/tn-TK/out-OSPF/instP-EPG1 due to Prefix Entry Already Used in Another EPG, debug message: prefix-entry-already-in-use: Prefix entry sys/ctx-[vxlan-2883584]/pfx-[10.51.0.0/24] is in use;
dn               : topology/pod-1/node-103/local/svc-policyelem-id-0/uni/epp/rtd-[uni/tn-TK/out-OSPF/instP-EPG1]/nwissues/fault-F0467
# fault.Inst
descr            : Configuration failed for uni/tn-TK/out-OSPF/instP-EPG1 due to Prefix Entry Already Used in Another EPG, debug message: prefix-entry-already-in-use: Prefix entry sys/ctx-[vxlan-2883584]/pfx-[10.51.0.0/24] is in use;
dn               : topology/pod-1/node-104/local/svc-policyelem-id-0/uni/epp/rtd-[uni/tn-TK/out-OSPF/instP-EPG1]/nwissues/fault-F0467
admin@f1-apic1:techsupport>
```



**script**
```
admin@apic1:techsupport> python aci-preupgrade-validation-script.py
    ==== 2023-08-14T17-32-47-0700, Script Version v1.6.1  ====

!!!! Check https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script for Latest Release !!!!

To use a non-default Login Domain, enter apic#DOMAIN\\USERNAME
Enter username for APIC login          : admin
Enter password for corresponding User  :

Checking current APIC version (switch nodes are assumed to be on the same version)...3.2(5e)

--- omit ---

[Check 20/47] L3Out Subnets (F0467 prefix-entry-already-in-use)...                                                 FAIL - OUTAGE WARNING!!
  Fault  Failed L3Out EPG               VRF VNID  VRF Name  Prefix already in use  Recommended Action
  -----  ----------------               --------  --------  ---------------------  ------------------
  F0467  uni/tn-TK/out-OSPF/instP-EPG1  2883584   VRFA      10.51.0.0/24           Resolve the conflict by removing the faulted configuration for the overlapping prefix
  F0467  uni/tn-TK/out-OSPF/instP-EPG1  2883584   VRFA      10.51.0.0/24           Resolve the conflict by removing the faulted configuration for the overlapping prefix
```

**Comment by lingwa00** [comment]
@takishida

Thanks for your feedback. Let me provide more detailed info on this.

Target ACI fabric was running in 3.2(5e) release.
In Pre-upgrade check, there was no” F0467 prefix-entry-already-in-use” appear on the APIC GUI fault dashboard. Also Pre-upgrade validation script shows checking pass.
==== 2023-01-31T18-47-47+0900 ====
Checking current APIC version (switch nodes are assumed to be on the same version)...3.2(5e)
Gathering APIC Versions from Firmware Repository...
[1]: aci-apic-dk9.3.2.5e.bin
[2]: aci-apic-dk9.5.2.5c.bin
You have chosen version "aci-apic-dk9.5.2.5c.bin"
[Check 20/43] L3Out Subnets (F0467 prefix-entry-already-in-use)...                                                                    PASS

APIC and Spine switches were upgraded to 5.2(5c) firstly. In post-check, also don’t see ”F0467 prefix-entry-already-in-use” fault.
After upgrading Leaf to 5.2(5c), ” F0467 prefix-entry-already-in-use” fault raised. ::/1, 8000::/1, 0.0.0.0/1, 128.0.0.0/1 configured on both L3out-A and L3out-B in same VRF is the cause. Configurations exist before upgrade, but fault raised raised after upgrading Leaf to 5.2(5c).

ACI-Pre-Upgrade-Validation-Script item 20 seems expect to identify the duplicate L3Out Subnets issue, but it showed “PASS”.
Please let me know if any additional info required.

May I confirm what’s the Leaf switch version in your testbed where the duplicate l3out prefix configured, is that also 3.2(5e)? Based on findings in my case, whether or not duplicate prefix can be detected by F0467 fault might related to switch OS release.

**Comment by takishida** [comment]
Thanks for the details, @lingwa00.

It turns out the fault message was enhanced via [CSCvq93592 - I: Fault for l3extSubnet overlap (F0467) is too vague](https://bst.cloudapps.cisco.com/bugsearch/bug/CSCvq93592) and the script was looking for the message that was added after this. This is the reason why the script didn't detect the fault on older switch versions.

This is a bug in the script instead of a new validation. I'll update the issue title and the label accordingly and work on a fix.

FYI:
The fault itself is there on older versions as well, but it was raised by a leaf and the APIC GUI on older versions show those faults under the node itself in `Fabric > Inventory > Pod X > leaf X > Faults` (or `System > Faults`), but not under the tenant config that triggered the fault. This must be why you missed it in the GUI. This was also enhanced (not via CSCvq93592, but via another enhancement) which is why you see the same fault under the tenant on newer versions.

The fault description before CSCvq93592:
```
descr            : Configuration failed for uni/tn-TK/out-BGP/instP-EPG1 due to Prefix Entry Already Used in Another EPG, debug message: 
```

The fault description after CSCvq93592:
```
descr            : Configuration failed for uni/tn-TK/out-OSPF/instP-EPG1 due to Prefix Entry Already Used in Another EPG, debug message: prefix-entry-already-in-use: Prefix entry sys/ctx-[vxlan-2883584]/pfx-[10.51.0.0/24] is in use;
```

**Comment by takishida** [comment]
After d2e5051:

The script result with a matching fault before CSCvq93592 (i.e. older switch versions)
```
[Check  1/1] L3Out Subnets (F0467 prefix-entry-already-in-use)...                                                 FAIL - OUTAGE WARNING!!
  Fault  Failed L3Out EPG              VRF VNID  VRF Name  Prefix already in use                         Recommended Action
  -----  ----------------              --------  --------  ---------------------                         ------------------
  F0467  uni/tn-TK/out-BGP/instP-EPG1  --        --        Not described in the fault (version too old)  Resolve the conflict by removing the faulted configuration for the overlapping prefix
```

The script result with a matching fault after CSCvq93592 (i.e. newer switch versions)
```
[Check  1/1] L3Out Subnets (F0467 prefix-entry-already-in-use)...                                                 FAIL - OUTAGE WARNING!!
  Fault  Failed L3Out EPG               VRF VNID  VRF Name  Prefix already in use  Recommended Action
  -----  ----------------               --------  --------  ---------------------  ------------------
  F0467  uni/tn-TK/out-OSPF/instP-EPG1  2457600   VRFA      20.51.0.0/24           Resolve the conflict by removing the faulted configuration for the overlapping prefix
```
