### ISSUE TITLE
NewValidation: CSCwb08081 Set clause not applying if prefix list is empty or not explicitly matched

### ISSUE THREAD

**Issue by rg5147** [datacenter/ACI-Pre-Upgrade-Validation-Script#50]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[X ] - Config

[ ] - Bug

[ ] - Other

### What needs to be validated
For a config validation, describe the exact configuration to be validated

Step 1

moquery -c bgpPeer | grep dn | grep -v overlay-1 | cut -d "/" -f3,8

THis should give you the border leaf node ID , vrf and the peer IP

Step 2 - For each of the BL run the below command 
show ip bgp nei <peer IP> vrf <vrf> | grep "Inbound route-map"

show ip bgp nei 10.103.3.234 vrf 695365052:USER | grep "Inbound route-map"

Leaf-104# show ip bgp nei 10.103.3.234 vrf 695365052:USER | grep "Inbound route-map"
  Inbound route-map configured is imp-l3out-L3OUT_SDWAN_SOHO-peer-2359297, handle obtained
  
  This will give you the route map name

Step 3: Check the route map

  Leaf-104# show route-map imp-l3out-L3OUT_SDWAN_SOHO-peer-2359297
route-map imp-l3out-L3OUT_SDWAN_SOHO-peer-2359297, permit, sequence 4601 
  Match clauses:
    community  (community-list filter): peer32773-2359297-exc-ext-in-SDWAN-SOHO-TO-USER-IN1COMMUNITY_SDWAN_SOHO1COMMUNITY_SDWAN_SOHO-rgcom 
  Set clauses:
    local-preference 200
    community 65100:101 65100:500 65100:601 65381:4 additive 
    
 Step 4:
 Check if the route map has a community match clause only 
  If yes then you are susceptible to this issue

### Why it needs to be validated
Describe why it needs to be validated and what may happen if it's not validated.
Inbound route will not have the right attributes set which can affect other downstream actions matching on the set attributes

### Additional context
Add any other context about the feature request here.

**Comment by wilsonbc2** [comment]
Reworked the logic for this defect so that it is compatible with app release.

1) Query class MO rtctrlSubjP and children
2) For each rtctrlSubjP, if there exists any rtctrlMatchCommTerm ensure there also exists at least one rtctrlMatchRtDest.
3) If any route maps do not match the condition above, flag it and capture route-map name as well as rtctrlRtCtxPToSubjP tDn for associated l3outs

```
admin@apic1:~> icurl 'http://localhost:7777/api/class/rtctrlSubjP.xml?rsp-subtree=children' | xmllint --format -
Bad:
  <rtctrlSubjP annotation="" descr="" dn="uni/tn-RD-Routing/subj-MatchIngressComm" name="MatchIngressComm" nameAlias="" userdom=":all:">
    <rtctrlMatchCommTerm annotation="" descr="" name="match-ExtComm" nameAlias="" userdom=":all:"/>
  </rtctrlSubjP>

Good:
  <rtctrlSubjP annotation="" descr="" dn="uni/tn-RD-MPOD/subj-MATCH-COMM2" name="MATCH-COMM2" nameAlias="" userdom=":all:">
    <rtctrlMatchRtDest aggregate="yes" annotation="" descr="" fromPfxLen="0" ip="0.0.0.0/0" name="" nameAlias="" toPfxLen="0" userdom=":all:"/>
    <rtctrlMatchCommTerm annotation="" descr="" name="COMM2" nameAlias="" userdom=":all:"/>
  </rtctrlSubjP>
```
