### ISSUE TITLE
NewValidation:need the check to validate CSCwf80352

### ISSUE THREAD

**Issue by kuskovoi** [datacenter/ACI-Pre-Upgrade-Validation-Script#57]
it's a request to implement the check in pre_upgrade script against CSCwf80352

in short, if Fabric Name contains "#" or ";" - conversion script will truncate it; meaning APIC will have new fabric name after upgrade in sam.config. When switch reboots during upgrade it cannot join the fabric as it receives truncated fabric name which is not matching DME config.

updating the defect with more info upon confirming with DE team. thanks!

**Comment by monrog2** [comment]
added to script version v1.5.0
