### ISSUE TITLE
Multiple checks are failing due to script not able to login to host

### ISSUE THREAD

**Issue by dewildel** [datacenter/ACI-Pre-Upgrade-Validation-Script#58]
(use upvote :thumbsup: for attentions)
**Describe the bug**
Unable to login into APIC controllers to perform target version image compatibility and to check APIC SSD health.
Tested on three different ACI fabrics with different numbers of controllers and APIC versions. Same error output every time.

**Script output**
You have chosen version "aci-apic-dk9.5.2.7f.bin"

Collecting VPC Node IDs...**[Check  1/45] APIC Target version image and MD5 hash...**
              Checking APIC1......                                                                                                ERROR !!
              Checking APIC3......                                                                                                ERROR !!
              Checking APIC2......                                                                                                ERROR !!
                                                                                                                  FAIL - UPGRADE FAILURE!!
  APIC   Firmware  md5sum  Failure                                                   Recommended Action
  APIC1  -         -       ls command via ssh failed due to:**failed to login to host  -**
  APIC2  -         -       ls command via ssh failed due to:**failed to login to host  -**
  APIC3  -         -       ls command via ssh failed due to:**failed to login to host  -**

**[Check 15/45] APIC SSD Health...**
              Checking APIC1......                                                                                                ERROR !!
              Checking APIC2......                                                                                                ERROR !!
              Checking APIC3......                                                                                                ERROR !!
                                                                                                                  FAIL - UPGRADE FAILURE!!
  Pod  Node   Storage Unit  % lifetime remaining  Recommended Action
  1    APIC1  -             -                     -                   **failed to login to host**
  2    APIC2  -             -                     -                   **failed to login to host**
  3    APIC3  -             -                     -                   **failed to login to host**

**To Reproduce**
1. Run the script on version 3.2.7k with target version 5.2.7f
2. Run the script on version 4.2.7f with target version 5.2.7f
3. Run the script on version 5.2.7f with target version 5.2.7g
All the above tested with local admin account.

**Comment by monrog2** [comment]
Hello, and thanks for reporting.

I am able to reproduce this behavior under the following conditions:
1. The ACI Fabric's default login domain is **not** set to `Local`
2. The selected domain does not have an `admin` user.

Without specifying a login domain, all login attempts (including this scripts) will attempt to use your default domain.

If you wish to use the local `admin` account for the script, you can do the following:

### Workaround
#### Pre-Requisites
1. The ACI Fabric's `fallback` Domain points to the `Local` Realm
2. The `Fallback Domain Availability` is set to  `Always Available`

#### Workaround Steps
1. When running the pre-upgrade validation script, specify the domain (such as `fallback`) that contains the user account you wish to use for the script run:
```
user@apic:~> python aci-preupgrade-validation-script.py
    ==== 2023-07-07T11-11-17-0400, Script Version v1.4.0  ====

!!!! Check https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script for Latest Release !!!!

Enter username for APIC login          : apic#fallback\\admin
Enter password for corresponding User  : 

Checking current APIC version (switch nodes are assumed to be on the same version)...5.2(6e)

Gathering APIC Versions from Firmware Repository...

[1]: aci-apic-dk9.5.2.7g.bin

What is the Target Version?     : 1

You have chosen version "aci-apic-dk9.5.2.7g.bin"

Collecting VPC Node IDs...[Check  1/45] APIC Target version image and MD5 hash... 
              Checking a-apic1......                                                                                                  DONE
              Checking a-apic2......                                                                                                  DONE 
```

I'll look at adding a note in the script output/documentation that specifying a domain is an option.

**Comment by monrog2** [comment]
Added text to the script run to indicate that a domain can be specific:
```
user@apic1:techsupport> python aci-preupgrade-validation-script.py
    ==== 2023-08-10T08-49-51-0400, Script Version v1.6.0  ====

!!!! Check https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script for Latest Release !!!!

To use a non-default Login Domain, enter apic#DOMAIN\\USERNAME
Enter username for APIC login          : apic#fallback\\admin
Enter password for corresponding User  :
