### ISSUE TITLE
"name 'file' is not defined" is shown in some checks.

### ISSUE THREAD

**Issue by machikaneko** [datacenter/ACI-Pre-Upgrade-Validation-Script#67]
**Describe the bug**
I executed aci-preupgrade-validation-script.py on 6.0(2h).
I got `name 'file' is not defined` as an exception in some checks.

**Script output**
Like below
```
Checking current APIC version (switch nodes are assumed to be on the same version)...6.0(2h)

Gathering APIC Versions from Firmware Repository...

[1]: aci-apic-dk9.6.0.3d.bin

What is the Target Version?     : 1

You have chosen version "aci-apic-dk9.6.0.3d.bin"

Collecting VPC Node IDs...

[Check  1/47] APIC Target version image and MD5 hash...
              Checking apic1......                                                                                                ERROR !!
                                                                                                                  FAIL - UPGRADE FAILURE!!
  APIC        Firmware  md5sum  Failure                     Recommended Action
  ----        --------  ------  -------                     ------------------
  apic1       -         -       name 'file' is not defined  -                                              <<<<<<<<<<<<<<<<<<<<<<<<<
```

**To Reproduce**
Steps to reproduce the behavior such as:
1. Add APIC image from APIC GUI > Admin > Firmware > Images > Actions > Add firmware
2. Confirm that the image has been added.
3. Run aci-preupgrade-validation-script.py
4. Select the added image.

**Expected behavior**
Users do not get this exception, `name 'file' is not defined`.

**Additional context**
I found that `file` function was used in `def start_log` of `class Connection`.
`file` function is one of Built-in Functions in Python2 and it is no longer used in Python3.
Python3 is used in Version 6.0(2h).
```
apic1# acidiag version
6.0.2h

apic1# python -V
Python 3.8.10
```
Please see the following documents.

https://docs.python.org/2.7/library/functions.html#file
https://docs.python.org/3.8/library/functions.html

In the above Python2 doc, it is recommended to use `open` function over `file` function.
```
When opening a file, it’s preferable to use open() instead of invoking this constructor directly. file is more suited to type testing (for example, writing isinstance(f, file)).
```
Could you please use `open` or other alternatives instead of `file`?

**Comment by monrog2** [comment]
Thanks for the catch. Easily reproducible in local labs with your details, will get a fix out.

**Comment by machikaneko** [comment]
Thank you for fixing it!
