### ISSUE TITLE
NewValidation: CSCwf00416 ACI 16.0.2 leaf sends manually configured intf description as port description in lldp instead of dn

### ISSUE THREAD

**Issue by rg5147** [datacenter/ACI-Pre-Upgrade-Validation-Script#77]
(use upvote :thumbsup: for attentions)
### Validation Type
[ ] - Fault

[ ] - Config

[ x] - Bug

[ ] - Other

### What needs to be validated
For a bug validation, describe the bug ID (ex. CSCxx12345) and the brief description of the bug in the context of pre-upgrade validations.
[CSCwf00416] ACI 16.0.2 leaf sends manually configured intf description as port description in lldp instead of dn

1. Check if there are any interface profile that has a desc configured. If there is one then we need to find our if that interface profile is tied to a VMM doamian
moquery -c infraAccPortP | egrep "^dn|desc"

2. Get a list of all the vmm domain that has on demand attachment. This issue affects only vmm doamin with on demand resolution
a-apic1# moquery -c fvRsDomAtt | egrep -B 16 "instrImedcy          : lazy" | grep "dn*.*vmmp"

3. Find the AEP associated with vmm domain. This will help get the policy group tied to the AEP.
a-apic1# moquery -c infraRtDomP | grep ^dn | grep vmmp

4. get the policy group associated with the specfic VMM AEPs
a-apic1# moquery -c infraRtAttEntP | grep ^dn

5. See which Interface Profile has the specfic policy group associated with the VMM AEPs and whether there is a description associated with that profile
a-apic1# moquery -c infraAccPortP -x rsp-subtree=full | egrep -A 18 "infra.AccPortP|infra.RsAccBaseGrp" | egrep "^dn|^desc|^    dn|^    tDn"

6. If there is description associated with that profile then we need to flag it.

### Why it needs to be validated
Vlans will not be deployed on the leaf

### Additional context
Add any other context about the feature request here.

**Comment by wilsonbc2** [comment]
Since issue is only in 6.0.1 and 6.0.2 which customers should not be targeting today, we will do simple check for VMM domain=lazy and custom interface descriptions exist. Check is still necessary due to the severity of the issue.
