### ISSUE TITLE
Check 27/49 mentions a non-existent class name.

### ISSUE THREAD

**Issue by andaluspc** [datacenter/ACI-Pre-Upgrade-Validation-Script#80]
**Describe the bug**
The script mentions class **actrlPrefix**. But such class doesn't seem to exist.

**Script output**
[Check 27/49] HW Programming Failure (F3544 L3Out Prefixes, F3545 Contracts, actrl-resource-unavailable)...          MANUAL CHECK REQUIRED
  Object Class  Recommended Action
#------------------------------
  **actrlPrefix**   Check that "operSt" are set to "enabled". F3544 does not exist on this version.
  actrlRule     Check that "operSt" are set to "enabled". F3545 does not exist on this version.

**To Reproduce**
Nothing specific.

**Expected behavior**
We expect to find class **actrlPrefix**. We don't see it exists anywhere in ACI versions 3.2, 4.2 or 5.2.

**Additional context**
Probably this an incorrect class name that need to be updated. A closest class name that we think close and relevant is **actrlPfxEntry**. We are not sure if this is the right class to check.

We are testing with ACI 3.2 trying to upgrade to 4.2.

**Comment by welkin-he** [comment]
Thanks  Amjad for reporting this issue, it appears there are a couple of typos for the className, the fix is committed and pending review. 

It looks there https://github.com/datacenter/ACI-Pre-Upgrade-Validation-Script/tree/welkin-issue-80
